[metadata]
generated_at = "2025-06-19T12:02:12.664"
eegfun_version = "0.1.0"
git_commit = "378f686758ae43178004b5365da3c179eed3919c"

[preprocess]
epoch_start = -1
epoch_end = 1
reference_channel = "avg"

    [preprocess.eog]
    extreme_value_criterion = 100
    hEOG_criterion = 30
    vEOG_criterion = 50

    [preprocess.layout]
    neighbour_criterion = 40

[files.output]
exit_early = false
save_ica_data = true
save_continuous_data = false
save_epoch_data = true
save_erp_data = true
directory = "../output_data"

[files.input]
layout_file = "biosemi72.csv"
raw_data_files = ["Flank_C_3.bdf"]
epoch_condition_file = "epochs.toml"
directory = ".."

[ica]
run = false

    [ica.filter]
    cutoff = 1
    order = 1
    on = true
    type = "fir"

[filter.lowpass]
cutoff = 40
order = 3
on = true
type = "fir"

[filter.highpass]
cutoff = 0.1
order = 1
on = true
type = "fir"
