[metadata]
generated_at = "2025-06-21T15:07:33.068"
eegfun_version = "0.1.0"
git_commit = "6ad7284da813a6c854cbf4fb25f2caf70a1971ba"

[preprocess]
epoch_start = -1
epoch_end = 1
reference_channel = "avg"

    [preprocess.eog]
    extreme_value_criterion = 100
    hEOG_criterion = 30
    hEOG_channels = [["F9"], ["F10"], ["hEOG"]]
    vEOG_channels = [["Fp1", "IO1"], ["Fp2", "IO2"], ["vEOG"]]
    vEOG_criterion = 50

    [preprocess.layout]
    neighbour_criterion = 40

[files.output]
exit_early = false
save_ica_data = true
save_continuous_data = false
save_erp_data_cleaned = true
save_epoch_data_cleaned = true
save_epoch_data_original = true
save_erp_data_original = true
directory = "../output_data"

[files.input]
layout_file = "biosemi72.csv"
raw_data_files = ["Flank_C_3.bdf"]
epoch_condition_file = "epochs.toml"
directory = ".."

[ica]
run = true

    [ica.ica_filter.lowpass]
    cutoff = 30
    order = 2
    on = true
    type = "fir"

    [ica.ica_filter.highpass]
    cutoff = 1
    order = 1
    on = true
    type = "fir"

[filter.lowpass]
cutoff = 40
order = 3
on = true
type = "fir"

[filter.highpass]
cutoff = 0.1
order = 1
on = true
type = "fir"
