[metadata]
average_neighbours_per_electrode = 2.69
total_electrodes = 72
generated_at = "2025-06-10T20:45:28.589"

[electrodes.Fp1]
neighbors = ["AF3"]
distances = [29.7746]
weights = [1.0]
neighbor_count = 1

[electrodes.AF7]
neighbors = ["F5", "F7"]
distances = [35.7749, 39.3308]
weights = [0.523673, 0.476327]
neighbor_count = 2

[electrodes.AF3]
neighbors = ["Fp1", "F1", "F3"]
distances = [29.7746, 36.8974, 35.6907]
weights = [0.378616, 0.305527, 0.315857]
neighbor_count = 3

[electrodes.F1]
neighbors = ["AF3", "F3", "FC1", "Fz"]
distances = [36.8974, 29.2292, 36.9376, 28.773]
weights = [0.220089, 0.277828, 0.219849, 0.282233]
neighbor_count = 4

[electrodes.F3]
neighbors = ["AF3", "F1", "F5", "FC3"]
distances = [35.6907, 29.2292, 29.2114, 36.8924]
weights = [0.226742, 0.276866, 0.277035, 0.219356]
neighbor_count = 4

[electrodes.F5]
neighbors = ["AF7", "F3", "F7", "FC5"]
distances = [35.7749, 29.2114, 28.3834, 39.4061]
weights = [0.227637, 0.278784, 0.286918, 0.206661]
neighbor_count = 4

[electrodes.F7]
neighbors = ["AF7", "F5", "F9"]
distances = [39.3308, 28.3834, 35.4329]
weights = [0.286065, 0.3964, 0.317535]
neighbor_count = 3

[electrodes.FT7]
neighbors = ["FC5"]
distances = [32.9019]
weights = [1.0]
neighbor_count = 1

[electrodes.FC5]
neighbors = ["F5", "FT7", "FC3", "C5"]
distances = [39.4061, 32.9019, 34.1342, 39.3013]
weights = [0.229632, 0.275027, 0.265098, 0.230244]
neighbor_count = 4

[electrodes.FC3]
neighbors = ["F3", "FC5", "FC1", "C3"]
distances = [36.8924, 34.1342, 33.0778, 36.1649]
weights = [0.237178, 0.256343, 0.26453, 0.241949]
neighbor_count = 4

[electrodes.FC1]
neighbors = ["F1", "FC3", "C1", "FCz"]
distances = [36.9376, 33.0778, 34.7579, 34.7579]
weights = [0.235732, 0.263239, 0.250515, 0.250515]
neighbor_count = 4

[electrodes.C1]
neighbors = ["FC1", "C3", "CP1", "Cz"]
distances = [34.7579, 35.3255, 34.7579, 35.3255]
weights = [0.252025, 0.247975, 0.252025, 0.247975]
neighbor_count = 4

[electrodes.C3]
neighbors = ["FC3", "C1", "C5", "CP3"]
distances = [36.1649, 35.3255, 35.3255, 36.1649]
weights = [0.247064, 0.252936, 0.252936, 0.247064]
neighbor_count = 4

[electrodes.C5]
neighbors = ["FC5", "C3", "T7", "CP5"]
distances = [39.3013, 35.3255, 35.3255, 39.3013]
weights = [0.236681, 0.263319, 0.263319, 0.236681]
neighbor_count = 4

[electrodes.T7]
neighbors = ["C5"]
distances = [35.3255]
weights = [1.0]
neighbor_count = 1

[electrodes.TP7]
neighbors = ["CP5"]
distances = [32.9019]
weights = [1.0]
neighbor_count = 1

[electrodes.CP5]
neighbors = ["C5", "TP7", "CP3", "P5"]
distances = [39.3013, 32.9019, 34.1342, 39.4061]
weights = [0.230244, 0.275027, 0.265098, 0.229632]
neighbor_count = 4

[electrodes.CP3]
neighbors = ["C3", "CP5", "CP1", "P3"]
distances = [36.1649, 34.1342, 33.0778, 36.8924]
weights = [0.241949, 0.256343, 0.26453, 0.237178]
neighbor_count = 4

[electrodes.CP1]
neighbors = ["C1", "CP3", "P1", "CPz"]
distances = [34.7579, 33.0778, 36.9376, 34.7579]
weights = [0.250515, 0.263239, 0.235732, 0.250515]
neighbor_count = 4

[electrodes.P1]
neighbors = ["CP1", "P3", "PO3", "Pz"]
distances = [36.9376, 29.2292, 36.8974, 28.773]
weights = [0.219849, 0.277828, 0.220089, 0.282233]
neighbor_count = 4

[electrodes.P3]
neighbors = ["CP3", "P1", "P5", "PO3"]
distances = [36.8924, 29.2292, 29.2114, 35.6907]
weights = [0.219356, 0.276866, 0.277035, 0.226742]
neighbor_count = 4

[electrodes.P5]
neighbors = ["CP5", "P3", "P7", "PO7"]
distances = [39.4061, 29.2114, 28.3834, 38.9369]
weights = [0.210553, 0.284035, 0.292322, 0.21309]
neighbor_count = 4

[electrodes.P7]
neighbors = ["P5"]
distances = [28.3834]
weights = [1.0]
neighbor_count = 1

[electrodes.P9]
neighbors = []
distances = []
weights = []
neighbor_count = 0

[electrodes.PO7]
neighbors = ["P5", "PO3"]
distances = [38.9369, 39.8438]
weights = [0.505755, 0.494245]
neighbor_count = 2

[electrodes.PO3]
neighbors = ["P1", "P3", "PO7", "O1"]
distances = [36.8974, 35.6907, 39.8438, 29.7746]
weights = [0.238147, 0.246199, 0.220537, 0.295118]
neighbor_count = 4

[electrodes.O1]
neighbors = ["PO3", "PO9"]
distances = [29.7746, 37.0065]
weights = [0.554146, 0.445854]
neighbor_count = 2

[electrodes.Iz]
neighbors = ["Oz"]
distances = [35.3255]
weights = [1.0]
neighbor_count = 1

[electrodes.Oz]
neighbors = ["Iz", "POz"]
distances = [35.3255, 35.3255]
weights = [0.5, 0.5]
neighbor_count = 2

[electrodes.POz]
neighbors = ["Oz", "Pz"]
distances = [35.3255, 35.3255]
weights = [0.5, 0.5]
neighbor_count = 2

[electrodes.Pz]
neighbors = ["P1", "POz", "CPz", "P2"]
distances = [28.773, 35.3255, 35.3255, 28.773]
weights = [0.275556, 0.224444, 0.224444, 0.275556]
neighbor_count = 4

[electrodes.CPz]
neighbors = ["CP1", "Pz", "Cz", "CP2"]
distances = [34.7579, 35.3255, 35.3255, 34.7579]
weights = [0.252025, 0.247975, 0.247975, 0.252025]
neighbor_count = 4

[electrodes.Fpz]
neighbors = ["AFz"]
distances = [35.3255]
weights = [1.0]
neighbor_count = 1

[electrodes.Fp2]
neighbors = ["AF4"]
distances = [29.7746]
weights = [1.0]
neighbor_count = 1

[electrodes.AF8]
neighbors = ["F6", "F8"]
distances = [35.7749, 39.3308]
weights = [0.523673, 0.476327]
neighbor_count = 2

[electrodes.AF4]
neighbors = ["Fp2", "F2", "F4"]
distances = [29.7746, 36.8974, 35.6907]
weights = [0.378616, 0.305527, 0.315857]
neighbor_count = 3

[electrodes.AFz]
neighbors = ["Fpz", "Fz"]
distances = [35.3255, 35.3255]
weights = [0.5, 0.5]
neighbor_count = 2

[electrodes.Fz]
neighbors = ["F1", "AFz", "F2", "FCz"]
distances = [28.773, 35.3255, 28.773, 35.3255]
weights = [0.275556, 0.224444, 0.275556, 0.224444]
neighbor_count = 4

[electrodes.F2]
neighbors = ["AF4", "Fz", "F4", "FC2"]
distances = [36.8974, 28.773, 29.2292, 36.9376]
weights = [0.220089, 0.282233, 0.277828, 0.219849]
neighbor_count = 4

[electrodes.F4]
neighbors = ["AF4", "F2", "F6", "FC4"]
distances = [35.6907, 29.2292, 29.2114, 36.8924]
weights = [0.226742, 0.276866, 0.277035, 0.219356]
neighbor_count = 4

[electrodes.F6]
neighbors = ["AF8", "F4", "F8", "FC6"]
distances = [35.7749, 29.2114, 28.3834, 39.4061]
weights = [0.227637, 0.278784, 0.286918, 0.206661]
neighbor_count = 4

[electrodes.F8]
neighbors = ["AF8", "F6", "F10"]
distances = [39.3308, 28.3834, 35.4329]
weights = [0.286065, 0.3964, 0.317535]
neighbor_count = 3

[electrodes.FT8]
neighbors = ["FC6"]
distances = [32.9019]
weights = [1.0]
neighbor_count = 1

[electrodes.FC6]
neighbors = ["F6", "FT8", "FC4", "C6"]
distances = [39.4061, 32.9019, 34.1342, 39.3013]
weights = [0.229632, 0.275027, 0.265098, 0.230244]
neighbor_count = 4

[electrodes.FC4]
neighbors = ["F4", "FC6", "FC2", "C4"]
distances = [36.8924, 34.1342, 33.0778, 36.1649]
weights = [0.237178, 0.256343, 0.26453, 0.241949]
neighbor_count = 4

[electrodes.FC2]
neighbors = ["F2", "FC4", "FCz", "C2"]
distances = [36.9376, 33.0778, 34.7579, 34.7579]
weights = [0.235732, 0.263239, 0.250515, 0.250515]
neighbor_count = 4

[electrodes.FCz]
neighbors = ["FC1", "Fz", "FC2", "Cz"]
distances = [34.7579, 35.3255, 34.7579, 35.3255]
weights = [0.252025, 0.247975, 0.252025, 0.247975]
neighbor_count = 4

[electrodes.Cz]
neighbors = ["C1", "CPz", "FCz", "C2"]
distances = [35.3255, 35.3255, 35.3255, 35.3255]
weights = [0.25, 0.25, 0.25, 0.25]
neighbor_count = 4

[electrodes.C2]
neighbors = ["FC2", "Cz", "C4", "CP2"]
distances = [34.7579, 35.3255, 35.3255, 34.7579]
weights = [0.252025, 0.247975, 0.247975, 0.252025]
neighbor_count = 4

[electrodes.C4]
neighbors = ["FC4", "C2", "C6", "CP4"]
distances = [36.1649, 35.3255, 35.3255, 36.1649]
weights = [0.247064, 0.252936, 0.252936, 0.247064]
neighbor_count = 4

[electrodes.C6]
neighbors = ["FC6", "C4", "T8", "CP6"]
distances = [39.3013, 35.3255, 35.3255, 39.3013]
weights = [0.236681, 0.263319, 0.263319, 0.236681]
neighbor_count = 4

[electrodes.T8]
neighbors = ["C6"]
distances = [35.3255]
weights = [1.0]
neighbor_count = 1

[electrodes.TP8]
neighbors = ["CP6"]
distances = [32.9019]
weights = [1.0]
neighbor_count = 1

[electrodes.CP6]
neighbors = ["C6", "TP8", "CP4", "P6"]
distances = [39.3013, 32.9019, 34.1342, 39.4061]
weights = [0.230244, 0.275027, 0.265098, 0.229632]
neighbor_count = 4

[electrodes.CP4]
neighbors = ["C4", "CP6", "CP2", "P4"]
distances = [36.1649, 34.1342, 33.0778, 36.8924]
weights = [0.241949, 0.256343, 0.26453, 0.237178]
neighbor_count = 4

[electrodes.CP2]
neighbors = ["CPz", "C2", "CP4", "P2"]
distances = [34.7579, 34.7579, 33.0778, 36.9376]
weights = [0.250515, 0.250515, 0.263239, 0.235732]
neighbor_count = 4

[electrodes.P2]
neighbors = ["Pz", "CP2", "P4", "PO4"]
distances = [28.773, 36.9376, 29.2292, 36.8974]
weights = [0.282233, 0.219849, 0.277828, 0.220089]
neighbor_count = 4

[electrodes.P4]
neighbors = ["CP4", "P2", "P6", "PO4"]
distances = [36.8924, 29.2292, 29.2114, 35.6907]
weights = [0.219356, 0.276866, 0.277035, 0.226742]
neighbor_count = 4

[electrodes.P6]
neighbors = ["CP6", "P4", "P8", "PO8"]
distances = [39.4061, 29.2114, 28.3834, 38.9369]
weights = [0.210553, 0.284035, 0.292322, 0.21309]
neighbor_count = 4

[electrodes.P8]
neighbors = ["P6"]
distances = [28.3834]
weights = [1.0]
neighbor_count = 1

[electrodes.P10]
neighbors = []
distances = []
weights = []
neighbor_count = 0

[electrodes.PO8]
neighbors = ["P6", "PO4"]
distances = [38.9369, 39.8438]
weights = [0.505755, 0.494245]
neighbor_count = 2

[electrodes.PO4]
neighbors = ["P2", "P4", "PO8", "O2"]
distances = [36.8974, 35.6907, 39.8438, 29.7746]
weights = [0.238147, 0.246199, 0.220537, 0.295118]
neighbor_count = 4

[electrodes.O2]
neighbors = ["PO4", "PO10"]
distances = [29.7746, 37.0065]
weights = [0.554146, 0.445854]
neighbor_count = 2

[electrodes.PO9]
neighbors = ["O1"]
distances = [37.0065]
weights = [1.0]
neighbor_count = 1

[electrodes.PO10]
neighbors = ["O2"]
distances = [37.0065]
weights = [1.0]
neighbor_count = 1

[electrodes.F9]
neighbors = ["F7"]
distances = [35.4329]
weights = [1.0]
neighbor_count = 1

[electrodes.F10]
neighbors = ["F8"]
distances = [35.4329]
weights = [1.0]
neighbor_count = 1

[electrodes.IO1]
neighbors = []
distances = []
weights = []
neighbor_count = 0

[electrodes.IO2]
neighbors = []
distances = []
weights = []
neighbor_count = 0

[electrodes.M1]
neighbors = []
distances = []
weights = []
neighbor_count = 0

[electrodes.M2]
neighbors = []
distances = []
weights = []
neighbor_count = 0
