[epochs]

[[epochs.conditions]]
name = "condition_1"
trigger_sequences = [[1]]

[[epochs.conditions]]
name = "condition_2"
trigger_sequences = [[4]]

[[epochs.conditions]]
name = "condition_3" 
trigger_sequences = [[5]]

[[epochs.conditions]]
name = "condition_4"
trigger_sequences = [[3]]