[files.input]
directory = ".."
raw_data_files = "Flank_C_3.bdf"
# raw_data_files = ["Flank_C_3.bdf"]
# raw_data_files = ["Flank_C_3.bdf", "Flank_C_4.bdf"]
# raw_data_files = "\\.bdf$"
# raw_data_files = "Flank_C_[^3]\\.bdf$"
# raw_data_files = "Flank_C_(?!7|14|28)([1-9]|[123][0-9])\\.bdf$"
layout_file = "biosemi72.csv"
epoch_condition_file = "epochs.toml"

[preprocess]
reference_channel = "avg"
epoch_start = -1.0
epoch_end = 3.0

[preprocess.filter]
highpass.apply = true
highpass.type = "hp"
highpass.freq = 0.1
highpass.method = "iir"
highpass.func = "filtfilt"
highpass.order = 1

lowpass.apply = true
lowpass.type = "lp"
lowpass.freq = 30.0
lowpass.method = "iir"
lowpass.func = "filtfilt"
lowpass.order = 3

ica_highpass.apply = true
ica_highpass.type = "hp"
ica_highpass.freq = 1.0
ica_highpass.method = "iir"
ica_highpass.func = "filtfilt"
ica_highpass.order = 1

ica_lowpass.apply = false
ica_lowpass.type = "lp"
ica_lowpass.freq = 30.0
ica_lowpass.method = "iir"
ica_lowpass.func = "filtfilt"
ica_lowpass.order = 3

[preprocess.eog]
vEOG_criterion = 50
hEOG_criterion = 30
vEOG_channels = [["Fp1", "Fp2"], ["IO1", "IO2"], ["vEOG"]]
hEOG_channels = [["F9"], ["F10"], ["hEOG"]]

[preprocess.eeg]
artifact_value_criterion = 100
extreme_value_criterion = 100

[preprocess.ica]
apply = true
percentage_of_data = 25.0

[files.output]
directory = "../output_data"
