name = "eegfun"
uuid = "aa15e9e4-a77e-4972-a32b-58bceaaa184b"
version = "0.1.0"
authors = ["igmmgi <ian.mackenzie@uni-tuebingen.de>"]

[deps]
AnovaFun = "786f6bac-1c88-4ef5-b24a-5b341b5d6c78"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BiosemiDataFormat = "d1c37e40-cd17-11e8-241b-47481c954d91"
BrainVisionDataFormat = "a1c37e40-cd17-11e8-241b-47481c954d92"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJLIBSVMInterface = "61c7150f-6c77-4bb1-949c-13197eac2a52"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJMultivariateStatsInterface = "1b6a4a23-ba22-4f51-9698-8599985d3728"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[sources]
BiosemiDataFormat = {rev = "master", url = "https://github.com/igmmgi/BiosemiDataFormat.jl.git"}
BrainVisionDataFormat = {rev = "main", url = "https://github.com/igmmgi/BrainVisionDataFormat.jl.git"}

[compat]
AnovaFun = "0.1.0"
BenchmarkTools = "1.6.3"
BiosemiDataFormat = "0.1.0"
BrainVisionDataFormat = "0.1.0"
CSV = "0.10.0"
CairoMakie = "0.15.2"
CategoricalArrays = "1.0.2"
Colors = "0.13.1"
DSP = "0.8.4"
DataFrames = "1.7.0"
Distributions = "0.25.120"
DocStringExtensions = "0.9.5"
FFTW = "1.0.0"
GLMakie = "0.13.2"
Glob = "1.4.0"
HypothesisTests = "0.11.6"
Interpolations = "1"
JLD2 = "0.5.15"
LIBSVM = "0.8.1"
LanguageServer = "4.1.0"
LoggingExtras = "1.0.0"
MLJ = "0.22.0"
MLJLIBSVMInterface = "0.2.2"
MLJLinearModels = "0.10.1"
Makie = "0.24.0"
NativeFileDialog = "0.2.1"
OrderedCollections = "1.4.0"
PrettyTables = "3.0.0"
ProfileView = "1.10.2"
ProgressMeter = "1.11.0"
ScatteredInterpolation = "0.3.0"
StatsBase = "0.34.6"
TOML = "1.0.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
CoverageTools = "c36e975a-824b-4404-a568-ef97ca766997"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
dev = ["Revise", "JuliaFormatter"]
docs = ["Documenter", "DocumenterTools"]
test = ["Test", "Coverage", "CoverageTools", "BenchmarkTools", "HypothesisTests"]
