# File paths and settings
[files.input]
raw_data_directory = "."
raw_data_files = ""
layout_file = ""

[files.output]
output_data_directory = "data/processed"
save_continuous_data = true
save_ica_data = true
save_epoch_data = true
save_erp_data = true
exit_early = false
delete_current_files = true
