[filtering]
highpass = { 
    value = 0.1, 
    type = "number", 
    min = 0.01, 
    max = 20, 
    description = "High-pass filter cutoff in Hz"
    }
lowpass = {
    value = 40.0, 
    type = "number", 
    min = 1.0, 
    max = 100.0, 
    description = "Low-pass filter cutoff in Hz"
    }